name: multiple_env_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  generate: true

  # assets:
  #   - config2/env.uat.json
  #   - config2/env.dev.json
  #   - config2/env.prod.json
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg